version: '3.8'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      #POSTGRES_DB: shopdb
    ports:
      - "5432:5432"